### PR TITLE
Update hr.json

### PR DESCRIPTION
**Pull request by WebShapedBiz**
Fine tuning

### CODE REVIEW

**Review by couellet — DISMISSED** [review]
Looks like many locales were removed in this PR, `view_detailed_cart` for instance. Please add missing locales and we'll then merge this one.

**Comment by WebShapedBiz** [comment]
Sorry for this oversight, I'll fix it immediately.
At this point I'm not familiar with the procedure, should I update the file and make a new PR, or is it enough just to update the file?

Thank you for your support.

**Comment by dominic-blain** [comment]
Hi @WebShapedBiz 

You can simply update the file and push to this branch. 
The PR will reflect the new changes ;)

Thanks!

**Review by dominic-blain — APPROVED** [review]

**Review by dominic-blain — APPROVED** [review]

**Comment by dominic-blain** [comment]
@WebShapedBiz Merged! 🥳

**Comment by WebShapedBiz** [comment]
Thank you @dominic-blain for your trouble. I hope I'll never have to fix this again, for the sake of both of us ;-)

Cheers.

**Comment by dominic-blain** [comment]
It was no trouble at all, thanks for your contributions! 👍

**Pull request merged**
