### PR TITLE
Update of CS translation

### PR DESCRIPTION
**Pull request by jonasNobile**
Is it possible to add more declensions than singular/plural? We have it little more complicated in Czech.

```json
"recurrence": {
    "daily": "day |||| %{smart_count} days",
}
```

Needs to be in Czech:
```
1 den
2 dny
3 dny
4 dny
5 dnů
6 dnů
... then it continues with dnů till the infinity.
```

### CODE REVIEW

**Comment by pgmichael** [comment]
Thanks for the contribution @jonasNobile! 

We use the polyglot.js library which does seem to support multiple forms of pluralization..

There's a Czech example in [this section of their README.md](https://github.com/airbnb/polyglot.js#pluralization).

**Review by pgmichael — APPROVED** [review]

**Comment by jonasNobile** [comment]
Thanks @pgmichael, I will make adjustments based on the example.

**Review by thatfrankdev — CHANGES_REQUESTED** [review]
>Thanks @pgmichael, I will make adjustments based on the example.

Hi @jonasNobile, can we assume you will push said changes in this PR? There's absolutely no rush here, I just want to make sure we don't release this by accident if it's not ready yet.

Thanks

**Comment by jonasNobile** [comment]
Hi @thatfrankdev, yes you assumed it right. It should be ok, now.

**Review by thatfrankdev — APPROVED** [review]
Looks good, Thanks @jonasNobile

**Pull request merged**
