### PR TITLE
nl locale added

### PR DESCRIPTION
**Pull request by erikgeelhuijzen**

### CODE REVIEW

**Comment by JeanSebTr** [comment]
Thanks for the contribution @erikgeelhuijzen !

I'll Squash (appearing like a single commit) this PR to remove the unrelated files changes. Be cautious about that next time 😉

**Comment by erikgeelhuijzen** [comment]
@JeanSebTr Thanks, this was my first time using GitHub. Sorry about the mistakes :-)

**Comment by erikgeelhuijzen** [comment]
@JeanSebTr Should I be able to use the locale nl already? I'm getting an error of resource not found: 
Failed to load resource: the server responded with a status of 404 ()
/#/:1 Access to fetch at 'https://cdn.snipcart.com/themes/v3.0.4/i18n/nl.json' from ....

**Comment by JeanSebTr** [comment]
I've just deployed it, give it a try!

**Comment by erikgeelhuijzen** [comment]
@JeanSebTr Thanks, works now!

**Pull request merged**
