### PR TITLE
:globe_with_meridians: (zh) added new locale zh-TW

### PR DESCRIPTION
**Pull request by imgarylai**
I added the new locale, `zh-TW`. There are fields still in English, but it is okay. I left them in English purposely. Those English words are commonly used in people using and speaking in the Traditional Chinese region/area.

### CODE REVIEW

**Comment by imgarylai** [comment]
@couellet Thank you for accepting this PR. Is the new locale available now? 

I followed the instruction of setting up the locale, but it I didn’t work.

**Comment by JeanSebTr** [comment]
Hi @imgarylai 

Sorry we forgot to update you when merging the PR

It should be available by updating to V3.0.11

**Comment by imgarylai** [comment]
@JeanSebTr thank you for checking this. 

I'm sorry to bother you again. Is it possible to set the default local from the dashboard? I ask this question because I'm using gatsby to build my e-commerce site and I can only set the site lang through Helmet. In this case, it looks like that the lang attrs set or loaded after the document is ready. At this point, the locale config is not set properly for snipcart to load. 

Thus, I want to know is it possible I can set the locale from the dashboard. 

I don't know if my questions clear to you. If you got any problems to understand my question, please let me know, I will try my best to describe it again. 

Thank you for you patience.

**Comment by JeanSebTr** [comment]
Hi @imgarylai !

You'll have to set the lang attr at build time so it is available when the page load. It should work when gatsby is deployed as a static site.

Alternatively, you can [use the Javascript](https://docs.snipcart.com/v3/setup/localization#using-our-javascript-api) API to set the lang at run time.

**Pull request merged**
